name: Test that the project is runnable

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKER_RO_TOKEN: ${{ secrets.DOCKER_RO_TOKEN }}
  STATA_LICENSE: ${{ secrets.STATA_LICENSE }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test that the project is runnable
    steps:
    - name: Test that the project is runnable
      uses: opensafely/research-action@main
